# Python basics les 3: 03/03
## Collections!

In [97]:
list = [5,3,5.5,False, "test"]
list[0] = 0
list[-1] = "nog eens een test" # laatste element
for x in list:
    print(x)
print(list)
list += ["extra", "lijst"]
print(list)
print(list[-2]) # voorlaatste element
list.pop() # default laatste element eraf!
print(list) 
list.pop(0) # natuurlijk ook verwijderen op index
print(list)
list.append("op het einde")
print(list)
print(len(list))
list.reverse()
print(list)
# list.sort()  alleen van hetzelfde type!


0
3
5.5
False
nog eens een test
[0, 3, 5.5, False, 'nog eens een test']
[0, 3, 5.5, False, 'nog eens een test', 'extra', 'lijst']
extra
[0, 3, 5.5, False, 'nog eens een test', 'extra']
[3, 5.5, False, 'nog eens een test', 'extra']
[3, 5.5, False, 'nog eens een test', 'extra', 'op het einde']
6
['op het einde', 'extra', 'nog eens een test', False, 5.5, 3]


## Lijsten aanmaken

In [98]:
nrs = range(0,10)
print(nrs)
for x in nrs:
    print(x)
squares = [ x*2 for x in range(0,10,3) ]
print(squares)
squares = [ x**2 for x in range(0,10,2) ]
print(squares)

print (4 in squares)
string = "dit is een test"
for c in string:
    print(c)
print("a" in string)

range(0, 10)
0
1
2
3
4
5
6
7
8
9
[0, 6, 12, 18]
[0, 4, 16, 36, 64]
True
d
i
t
 
i
s
 
e
e
n
 
t
e
s
t
False


## 2D lijsten

In [99]:
list_2d = [ [1,2,3],[4,5,6],[7,8,9] ]
print(list_2d) 

for list in list_2d:
    for x in list:
        print(x, end="\t")
    print()


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
1	2	3	
4	5	6	
7	8	9	


## Collecties

[] voor list --> wijzigen, op index ophalen <br>
() voor tuple --> niet wijzigbaar! <br>
{} voor set & dictionary (dictionary --> key:value) --> enkel unieke waarden

wel altijd [] voor opvragen

In [100]:
tuple = ("winter", "lente", "zomer", "herfst")
print(tuple)
for i in tuple:
    print(i)
print(tuple[0])

# tuple[0] = "ander seizoen" --> lukt niet, is niet wijzigbaar!

set = {"appel", "banaan", "appelsien", "kiwi"}
print(set)
set.add("peer")
print(set)
set.add("peer")
print(set)
# print(set[0]) opvragen --> lukt niet!! multi-select set is handig (notion ;) hé renke!)

dictionary = { "a":"appel", "b":"banaan", "c":"citroen", "a": "avocado" }
print(dictionary)
dictionary["c"] = "cherry"
print(dictionary)


('winter', 'lente', 'zomer', 'herfst')
winter
lente
zomer
herfst
winter
{'appel', 'banaan', 'kiwi', 'appelsien'}
{'kiwi', 'appelsien', 'appel', 'peer', 'banaan'}
{'kiwi', 'appelsien', 'appel', 'peer', 'banaan'}
{'a': 'avocado', 'b': 'banaan', 'c': 'citroen'}
{'a': 'avocado', 'b': 'banaan', 'c': 'cherry'}


## Werken met packages

https://pypi.org/ 

### Arrays aanmaken

In [101]:
import numpy as np #import numpy

list = [1,2,3,4,5]
array = np.array(list)

print(list)
print(array)

print(list*2)
print(array*2)

print(np.arange(10))
print(np.zeros(10))
print(np.arange(0,100,3))
print(np.full((5,2),4))
print(np.full((1,2),4))
print(np.random.random(1))
print(np.random.random_integers(-10,10, (2,3)))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]
[[4 4]]
[0.95504562]
[[ 4 -8 -5]
 [ 7  9 -2]]


### Arrays aanpassen

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [102]:
array = np.arange(10)
print(array)

print(type(array))
print(array.dtype)

new_array = array.astype("f")
print(new_array)
print(new_array.dtype)

print(new_array.shape)

array_2d = np.reshape(array, (2,5))
print(array_2d)
print(array_2d.shape)
print(array_2d.ndim)

# array_2db = np.reshape(array, (3,3)) --> dimensies moeten kloppen!!!!

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2


### Arrays slicen

\[start:end:step\]<br>
als het leeg = default!!! <br>
start = leeg --> 0 <br>
end = leeg --> laatste element <br>
step = leeg --> 1<br>

geen dubbel punt = gewoon op index

In [77]:
array = np.arange(10)*2

print(array)
print(array[1])
print(array[1:3])
print(array[0:10:2])
print(array[::2])
print(array[1::2])
array[::3] = -5 # toewijzen!!!
print(array)
print(array[::-1])


[ 0  2  4  6  8 10 12 14 16 18]
2
[2 4]
[ 0  4  8 12 16]
[ 0  4  8 12 16]
[ 2  6 10 14 18]
[-5  2  4 -5  8 10 -5 14 16 -5]
[-5 16 14 -5 10  8 -5  4  2 -5]


### Bewerkingen met arrays

In [103]:
a = np.arange(0,10)
b = np.arange(10,0,-1)

print(a)
print(b)

c = a - b
print(c)
print(c > 0)

print(np.where(c>0))

c %= 3
print(c)

print(np.where(a%2 == 0, a+1, a)) # pythonic 
for x in a:
    if x % 2 == 0:
        print(x+1, end=" ")
    else:
        print(x, end=" ")
print()
array_2d = np.reshape(a, (5,2))
print(array_2d)

print(a.sum(axis = 0))
print(a.min(axis = 0))

[0 1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[False False False False False False  True  True  True  True]
(array([6, 7, 8, 9], dtype=int64),)
[2 1 0 2 1 0 2 1 0 2]
[1 1 3 3 5 5 7 7 9 9]
1 1 3 3 5 5 7 7 9 9 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
45
0


### It's magic time!


Read a 1D array and a number of rows! Convert this 1D array to a 2D array! Calculate the sum of each column and if all sums are equal... you are dealing with a magic table!


input <br>
2 7 0 8 4 1 1 0 10<br>
3<br>
output<br>
True<br>


2 7 0<br>
8 4 1<br>
1 0 10<br>


11 11 11 --> MAGIC TABLE

In [104]:
array = np.array([2, 7, 0, 8, 4, 1, 1, 0, 10])
rows = 3

array_2d = np.reshape(array, (rows, array.size//rows))
print(array_2d)

sums = array_2d.sum(axis = 0)
print(sums)

result = np.all(sums == sums[0])
print(result)

[[ 2  7  0]
 [ 8  4  1]
 [ 1  0 10]]
[11 11 11]
True
