# Les 4: Strings & regex

## Herhaling
You are given a NumPy array temperatures representing the daily maximum temperatures in degrees Celsius for a month. Write a Python script using NumPy to:

- Find the mean temperature for the month.
- Extract the temperatures for the last week of the month into a new array.
- Identify days (index positions) with temperatures above the monthly mean.

In [12]:
import numpy as np

# Sample data: daily max temperatures for a month
temperatures = np.array([22, 25, 19, 21, 24, 28, 23, 26, 27, 22, 20, 21, 25, 29, 30, 22, 24, 26, 28, 27, 25, 24, 22, 23, 26, 29, 28, 27, 25, 23])

# 1. Calculate the mean temperature for the month.
mean = np.mean(temperatures)
print(mean)

# 2. Slice the array to get temperatures for the last week.
lastweek = temperatures[-7::]
print(lastweek)

# 3. Find days with temperatures above the monthly mean.
above = np.where(temperatures > mean) # geeft indexen terug!
print(above)

above = np.array([x for x in temperatures if x > mean])
print(above)

above = [x for x in temperatures if x > mean]
print(above)

for temp in temperatures:
    if temp > mean:
        print(temp)

24.7
[23 26 29 28 27 25 23]
(array([ 1,  5,  7,  8, 12, 13, 14, 17, 18, 19, 20, 24, 25, 26, 27, 28],
      dtype=int64),)
[25 28 26 27 25 29 30 26 28 27 25 26 29 28 27 25]
[25, 28, 26, 27, 25, 29, 30, 26, 28, 27, 25, 26, 29, 28, 27, 25]
25
28
26
27
25
29
30
26
28
27
25
26
29
28
27
25


## Strings

Enkele & dubbele quotes + escapen can speciale tekens!

In [23]:
print("'s Avonds")
print('\'s Avonds')

print("Dit '\\' is het escape teken")

print("Dit \n neemt nieuwe lijn")
print("Dit \t neemt tab")

print(r"Dit '\\' is het escape teken")
print(r"Dit \t neemt tab")

print(r"Dit is een test '\\'" +  "Dit is een test '\\'")

's Avonds
's Avonds
Dit '\' is het escape teken
Dit 
 neemt nieuwe lijn
Dit 	 neemt tab
Dit '\\' is het escape teken
Dit \t neemt tab
Dit is een test '\\'Dit is een test '\'


Spelen in een string!

slicen --> [start:stop:stap]

in --> checken of er een karakter in de string zit!


In [39]:
abc = "abcdefghijklmnopqrstuvwxyz"

print(abc[-1]) # laatste karakter
print(abc[::-1])

print(abc[::2]) # alle even posities

print(abc[4:20:]) # van e naar t 
print(abc[19:3:-1]) # van t naar e

print("a" in "abc")
print("a" in abc)
print("é" in abc)

# abc.where lukt niet!

z
zyxwvutsrqponmlkjihgfedcba
acegikmoqsuwy
efghijklmnopqrst
tsrqponmlkjihgfe
True
True
False


In [42]:
import numpy as np

abc_array = np.array(list(abc)) # van string een lijst van karakters maken --> array steken
print(abc_array)

# met array kunnen we where gebruiken

np.where(abc_array == "e")

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


(array([4], dtype=int64),)

Splitten & Joinen van strings

In [50]:
zin ="Dit is een test zin \n nog een test"

print(zin.split())
print(zin.split("e"))
print(zin.split("\n"))

abc = ['a','b' ,'c', 'd', 'e' ,'f' ,'g' ,'h', 'i', 'j', 'k' ,'l' ,'m' ,'n', 'o', 'p', 'q' ,'r','s' ,'t' ,'u' ,'v', 'w' ,'x' ,'y' ,'z']
print("".join(abc))
print(" - ".join(abc))


['Dit', 'is', 'een', 'test', 'zin', 'nog', 'een', 'test']
['Dit is ', '', 'n t', 'st zin \n nog ', '', 'n t', 'st']
['Dit is een test zin ', ' nog een test']
abcdefghijklmnopqrstuvwxyz
a - b - c - d - e - f - g - h - i - j - k - l - m - n - o - p - q - r - s - t - u - v - w - x - y - z


- isX()-functies
- Strippen van de strings --> spaties vooraan & achteraan wegnemen

In [64]:
zin = "    Dit is 1 test     "

zin = zin.strip()

for karakter in zin:
    if karakter.islower():
        print(karakter.upper(),end=" ")
    elif karakter.isupper():
        print(karakter.lower(),end=" ")
    elif karakter.isdigit():
        print("DIGIT",end=" ")
    elif karakter.isspace():
        print("SPACE",end=" ")

print()
print(zin.startswith("D"))
print(zin.startswith("d"))

d I T SPACE I S SPACE DIGIT SPACE T E S T 
True
False


https://www.asciitable.com/


In [66]:
print(ord("a"))

print(chr(100))

97
d


Most words in Pig Latin end in "ay." Use the rules below to translate normal English into Pig Latin.

1. If a word starts with a consonant and a vowel, put the first letter of the word at the end of the word and add "ay." Example: Happy = appyh + ay = appyhay
2. If a word starts with two consonants move the two consonants to the end of the word and add "ay." Example: Child = Ildch + ay = Ildchay
3. If a word starts with a vowel add the word "way" at the end of the word. Example: Awesome = Awesome +way = Awesomeway

In [71]:
sentence = "This child is very loud".lower()
# isthay ildchay isway eryvay oudlay

words = sentence.split()
for word in words:
    if word[0] in "aeyuio":
        print(word+"way")
    else:
        if word[1] in "aeyuio":
            print(word[1::]+word[0]+"ay")
        else:
            print(word[2::]+word[0:2]+"ay")

isthay
ildchay
isway
eryvay
oudlay


## Packages/modules
The Python Standard Library: https://docs.python.org/3/library/index.html 

In [73]:
help('modules')


Please wait a moment while I gather a list of all available modules...



c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\google\auth\__init__.py:55: Python37DeprecationWarning: After January 1, 2024, new releases of this library will drop support for Python 3.7. More details about Python 3.7 support can be found at https://cloud.google.com/python/docs/python37-sunset/
  warnings.warn(message, Python37DeprecationWarning)
c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\google\oauth2\__init__.py:40: Python37DeprecationWarning: After January 1, 2024, new releases of this library will drop support for Python 3.7. More details about Python 3.7 support can be found at https://cloud.google.com/python/docs/python37-sunset/
  warnings.warn(message,

Hello this is my package!


c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\twitter\__init__.py:21: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  "The twython library has not been installed. "
c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")


pygame 2.3.0 (SDL 2.24.2, Python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\pkgutil.py:92: UserWarning: viewer requires Qt
  __import__(info.name)
c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\_sharded_tensor\__init__.py:10: DeprecationWarning: torch.distributed._sharded_tensor will be deprecated, use torch.distributed._shard.sharded_tensor instead
  DeprecationWarning
c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\_sharding_spec\__init__.py:10: DeprecationWarning: torch.distributed._sharding_spec will be deprecated, use torch.distributed._shard.sharding_spec instead
  DeprecationWarning
NOTE: Redirects are currently not supported in Windows or MacOs.
Using region Flanders server backend.
c:\Users\elkeb\AppData\Local\Programs\Python\Python37\lib\site-packages\twine\__init__.py:43: DeprecationWarning: Implicit None on return values is deprecated and will raise KeyErrors.
  __license__ = metadata["license"]
c:\Users\elk

Crypto              configparser        more_itertools      sre_parse
Cython              contextlib          morse               ssl
IPython             contextvars         morse3              sspi
OpenSSL             copy                msilib              sspicon
PIL                 copyreg             msvcrt              stat
PyPDF2              crypt               multidict           statistics
WhatToCook          cryptography        multiprocess        storemagic
__future__          cssselect           multiprocessing     string
_abc                csv                 munch               stringprep
_ast                ctypes              mypackage           struct
_asyncio            curses              mypy_extensions     structlog
_bisect             cv2                 mysql               subprocess
_blake2             cycler              mysqlx              sumy
_bootlocale         cython              nest_asyncio        sunau
_bz2                cythonmagic         netbios  

## Regex 
https://regexr.com/

In [ ]:
zin = "In 2024 ontdekten wetenschappers op Mars sporen van water, wat leidde tot grote opwinding. Tegen 2030 was de eerste bemande missie geland. In 2045 hadden we een permanente basis op Mars, bevolkt door 50 moedige zielen. Tegen 2050 was de bevolking gegroeid tot 150, een mijlpaal in interplanetaire kolonisatie."