# Les 3 - herhaling & pythonic code

## Herhalingsoefening
We gaan een script maken dat cijfers van studenten bijhoudt, een bonus berekent met NumPy en de resultaten presenteert via een pratende koe.
- Stap 1: Installatie - zorg dat je de library cowsay hebt geïnstalleerd (ga even kijken wat die doet op PyPI
- Stap 2: De Data - zorg dat je namen en cijfers kan bewaren
- Stap 3: Cijfers Invoeren
- Stap 4: De NumPy Bonus - Stel dat het examen erg moeilijk was en iedereen 2 punten bonus krijgt.
- Stap 5: Overzicht tonen Print per student: "Student [naam] heeft een [cijfer] behaald."
- Stap 6: De Koe - Bereken het gemiddelde van de eindcijfers en laat de koe via cowsay.cow() vertellen wat het klasgemiddelde is.

In [ ]:
# ! py -m pip install cowsay

import numpy as np
import cowsay

namen = ["jan", "piet", "joris", "korneel", "marie"]
cijfers = [5,2,8,6,7]
array = np.array(cijfers)

array += 2
# print(array+2) # dit lukt alleen maar als het een array is!!!
# studenten = {"jan":5, "piet":2, "joris":8, "korneel":6, "marie":7} # in een dictionary is het niet mogelijk om snel +2 te doen!!

for i in range(0,len(namen)):
    print("Student", namen[i], "heeft een", array[i], "behaald")

gemiddelde = np.average(array) # average kunnen we gewichten meegeven
print(gemiddelde)
print(array.mean()) # mean is gewone gemiddelde

cowsay.cow("Het gemiddelde is " + str(gemiddelde))

Student jan heeft een 7 behaald
Student piet heeft een 4 behaald
Student joris heeft een 10 behaald
Student korneel heeft een 8 behaald
Student marie heeft een 9 behaald
7.6
7.6
  ____________________
| Het gemiddelde is7.6 |
                    \
                     \
                       ^__^
                       (oo)\_______
                       (__)\       )\/\
                           ||----w |
                           ||     ||


## Slicing [start:end:step]

- inclusieve start
- exclusieve end

In [ ]:
array = np.arange(10)
print(array)

print(array[2::])
print(array[2:8:]) # excl 8
print(array[2::2])
print(array[::3])
print(array[::-1])

array[::3] = -10 # om de 3 elementen zet het op -10
print(array)

print(array[::2]) # even elementen
print(array[1::2]) # oneven elementen

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6 8]
[0 3 6 9]
[9 8 7 6 5 4 3 2 1 0]
[-10   1   2 -10   4   5 -10   7   8 -10]
[-10   2   4 -10   8]
[  1 -10   5   7 -10]
