# Les 3 - herhaling & pythonic code

## Herhalingsoefening
We gaan een script maken dat cijfers van studenten bijhoudt, een bonus berekent met NumPy en de resultaten presenteert via een pratende koe.
- Stap 1: Installatie - zorg dat je de library cowsay hebt geïnstalleerd (ga even kijken wat die doet op PyPI
- Stap 2: De Data - zorg dat je namen en cijfers kan bewaren
- Stap 3: Cijfers Invoeren
- Stap 4: De NumPy Bonus - Stel dat het examen erg moeilijk was en iedereen 2 punten bonus krijgt.
- Stap 5: Overzicht tonen Print per student: "Student [naam] heeft een [cijfer] behaald."
- Stap 6: De Koe - Bereken het gemiddelde van de eindcijfers en laat de koe via cowsay.cow() vertellen wat het klasgemiddelde is.

In [ ]:
# ! py -m pip install cowsay

import numpy as np
import cowsay

namen = ["jan", "piet", "joris", "korneel", "marie"]
cijfers = [5,2,8,6,7]
array = np.array(cijfers)

array += 2
# print(array+2) # dit lukt alleen maar als het een array is!!!
# studenten = {"jan":5, "piet":2, "joris":8, "korneel":6, "marie":7} # in een dictionary is het niet mogelijk om snel +2 te doen!!

for i in range(0,len(namen)):
    print("Student", namen[i], "heeft een", array[i], "behaald")

gemiddelde = np.average(array) # average kunnen we gewichten meegeven
print(gemiddelde)
print(array.mean()) # mean is gewone gemiddelde

cowsay.cow("Het gemiddelde is " + str(gemiddelde))

Student jan heeft een 7 behaald
Student piet heeft een 4 behaald
Student joris heeft een 10 behaald
Student korneel heeft een 8 behaald
Student marie heeft een 9 behaald
7.6
7.6
  ____________________
| Het gemiddelde is7.6 |
                    \
                     \
                       ^__^
                       (oo)\_______
                       (__)\       )\/\
                           ||----w |
                           ||     ||


## Slicing [start:end:step]

- inclusieve start
- exclusieve end

In [ ]:
array = np.arange(10)
print(array)

print(array[2::])
print(array[2:8:]) # excl 8
print(array[2::2])
print(array[::3])
print(array[::-1])

array[::3] = -10 # om de 3 elementen zet het op -10
print(array)

print(array[::2]) # even elementen
print(array[1::2]) # oneven elementen

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6 8]
[0 3 6 9]
[9 8 7 6 5 4 3 2 1 0]
[-10   1   2 -10   4   5 -10   7   8 -10]
[-10   2   4 -10   8]
[  1 -10   5   7 -10]


### Oefening
Je hebt een lijst met 24 temperatuurmetingen ontvangen, één voor elk uur van de dag (van 00:00 tot 23:00). Je doel is om specifieke dagdelen te isoleren en te analyseren met behulp van slicing.

- Maak een lijst genaamd metingen met 24 getallen (bijv. tussen de 5 en 20 graden).
- Gebruik slicing om de volgende sub-lijsten te maken :
  - De Ochtend-rush: Selecteer de temperaturen van de eerste 6 uur van de dag (index 0 tot 6).
  - De Late Avond: Selecteer de laatste 4 metingen van de dag. Eis: Gebruik hiervoor negatieve indexen.
  - De 'Trend' Check: Selecteer elke 3 uur een meting (dus 00:00, 03:00, 06:00, etc.) om een snelle trend te zien. Gebruik hiervoor de stepsize parameter.
  - De Middag-dip: Selecteer de uren tussen 12:00 en 18:00, maar toon deze in omgekeerde volgorde .
- Loop door je 'Trend' selectie en print de waarden.

In [50]:
import random 

temp = [random.randint(5,21) for x in range(25)]  # --> ne lijst
metingen = np.random.randint(5,21,24) # --> array

print(temp)
print(metingen)

ochtend = metingen[:6] # je begint te tellen vanaf 0!!! index 6 --> 7e element!!!
print(ochtend)

avond = temp[-4::]
print(avond)

trend = metingen[::3]
print(trend)
for i in range(0,len(trend)):
    print(i*3, "uur met temperatuur",trend[i])

middag = temp[18:11:-1]
print(middag)

[11, 17, 13, 10, 11, 15, 11, 21, 16, 10, 7, 5, 9, 9, 9, 12, 10, 6, 12, 7, 18, 11, 20, 21, 21]
[ 7  6  9 17  9 13 10 14 19 15 11  5 10 17  6 16 11  5 17 17  9  7 11  6]
[ 7  6  9 17  9 13]
[11, 20, 21, 21]
[ 7 17 10 15 10 16 17  7]
0 uur met temperatuur 7
3 uur met temperatuur 17
6 uur met temperatuur 10
9 uur met temperatuur 15
12 uur met temperatuur 10
15 uur met temperatuur 16
18 uur met temperatuur 17
21 uur met temperatuur 7
[12, 6, 10, 12, 9, 9, 9]
