# Les 3 - 28/2 - Python basics

## De echte basis
- collections
- numpy
- pythonic
- packages

## Collecties

- lijst [ ] --> kan je alles mee doen ;)
- tuple ( ) --> is vast
- set { } --> lijst waar geen dubbels inzitten!
- dictionary { key : value } 

In [1]:
lijst = []
lijst.append("een")
lijst.append(1)
print(lijst)

['een', 1]


In [2]:
dagen = ("maan","din","woens","donder","vrij","zater","zon")
for dag in dagen:
    print(dag+"dag")

maandag
dindag
woensdag
donderdag
vrijdag
zaterdag
zondag


In [3]:
recept = {"pasta", "eieren","parmezaan", "spek", "pezo"}

recept.add("pasta")
print(recept)

{'pezo', 'spek', 'eieren', 'pasta', 'parmezaan'}


In [6]:
studenten = {} #keys moeten uniek zijn!!

studenten["r564556"] = "sami"
studenten["r678990"] = "denzel"

print(studenten)

studenten["r564556"] = "sami 2"
print(studenten)

studenten["r563556"] = "sami"
print(studenten)

{'r564556': 'sami', 'r678990': 'denzel'}
{'r564556': 'sami 2', 'r678990': 'denzel'}
{'r564556': 'sami 2', 'r678990': 'denzel', 'r563556': 'sami'}


In [15]:
matrix = [ [1,2,3],[4,5,6],[7,8,9] ]
print(matrix)  #[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#[1, 2, 3]
#[4, 5, 6]
#[7, 8, 9]
for lijst in matrix:
    print(lijst)

#1 2 3
#4 5 6
#7 8 9
for rij in matrix:
    for element in rij:
        print(element, end=" ")
    print()


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
1 2 3 
4 5 6 
7 8 9 


You are organizing a party and have guests from various circles. 

friends = ["Alice", "Bob", "Charlie", "Dana", "Alice"]
colleagues = {"Eva", "Frank", "Grace"}
neighbors = ("Hugo", "Ivy")

special_notes = {
    "friends": "Bring a smile!",
    "colleagues": "Share a story.",
    "neighbors": "Share a local tip."
}

- Finalize Guest List: Combine friends (with duplicates removed), colleagues, and neighbors into a final guest list without duplicates.
- Prepare Welcome Packages: For each guest type (friends, colleagues, neighbors), print a welcome message including the special note from special_notes.

In [20]:
friends = ["Alice", "Bob", "Charlie", "Dana", "Alice"]
colleagues = {"Eva", "Frank", "Grace"}
neighbors = ("Hugo", "Ivy")

special_notes = {
    "friends": "Bring a smile!",
    "colleagues": "Share a story.",
    "neighbors": "Share a local tip."
}

guestlist = set()
for name in friends:
    guestlist.add(name+ " "+special_notes["friends"])

for name in colleagues:
    guestlist.add(name + " " + special_notes["colleagues"])

for name in neighbors:
    guestlist.add(name + " " + special_notes["neighbors"])

print(guestlist)

{'Hugo Share a local tip.', 'Bob Bring a smile!', 'Eva Share a story.', 'Grace Share a story.', 'Frank Share a story.', 'Dana Bring a smile!', 'Ivy Share a local tip.', 'Charlie Bring a smile!', 'Alice Bring a smile!'}


## Packages

- pip install package
- import package

In [21]:
! pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import numpy as np

list = [1,2,3,4]
print(list)

array = np.array(list)
print(array)

print(list*2)
print(array*2)

print(np.arange(10))
print(np.ones((10,5)))

print(np.full((2,4),4))
print(np.full((10,),4))
print(np.full((2,4),"x"))

print(np.random.random((2,4)))

[1, 2, 3, 4]
[1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[4 4 4 4]
 [4 4 4 4]]
[4 4 4 4 4 4 4 4 4 4]
[['x' 'x' 'x' 'x']
 ['x' 'x' 'x' 'x']]
[[0.33484427 0.87527868 0.27765877 0.11030749]
 [0.01851573 0.89196771 0.48977226 0.12161478]]


In [40]:
array = np.arange(10)
print(array)

print(type(array))
print(array.ndim)
print(array.shape)

matrix = array.reshape((5,2))
print(matrix)
print(matrix.ndim)
print(matrix.shape)

matrix = array.reshape((2,5))
print(matrix)
print(matrix.ndim)
print(matrix.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
2
(5, 2)
[[0 1 2 3 4]
 [5 6 7 8 9]]
2
(2, 5)


It's magic time!

Read a 1D array and a number of rows! Convert this 1D array to a 2D array! Calculate the sum of each column and if all sums are equal... you are dealing with a magic table!

input
2 7 0 8 4 1 1 0 10
3
output
True

2 7 0

In [62]:
input_array = "2 7 0 8 4 1 1 0 10".split() #input("Geef een array in").split()
input_rows = 3 #int(input("Geef aantal rijen in"))

print(input_array)

array = np.array(input_array).astype('i') # maakt van input array een np array én zet door astype() alles om naar ints!
print(array)

cols = len(input_array)//input_rows

matrix = array.reshape((input_rows,cols))
print(matrix)

sum_cols = matrix.sum(axis=0)
print(sum_cols)

# algoritmisch 
first = sum_cols[0]
magic = True
for element in sum_cols:
    if element != first:
        magic = False

print(magic)
    
# werken met een set
set_cols = set(sum_cols)
print(set_cols)
if len(set_cols) == 1:
    print(True)
else:
    print(False)

['2', '7', '0', '8', '4', '1', '1', '0', '10']
[ 2  7  0  8  4  1  1  0 10]
[[ 2  7  0]
 [ 8  4  1]
 [ 1  0 10]]
[11 11 11]
True
{11}
True


In [63]:
! pip install emoji


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [65]:
#how to use

import emoji
print(emoji.emojize('Python is :thumbs_up:'))

#now translate this 👨‍💻🐍➡️🎉🚀🌈📚
print(emoji.demojize("👨‍💻🐍➡️🎉🚀🌈📚"))

Python is 👍
:man_technologist::snake::right_arrow::party_popper::rocket::rainbow::books:


## Pythonic code

In [66]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [67]:
def is_anagram(str1, str2):
    # Remove spaces and lowercase the strings
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower()
    
    # Check if the sorted characters of both strings are equal
    if sorted(str1) == sorted(str2):
        return True
    else:
        return False

# Example usage
str1 = "Listen"
str2 = "Silent"
print(is_anagram(str1, str2))  # Output: True

True


In [ ]:
def is_anagram_pythonic(str1,str2):
    #code 

str1 = "Listen"
str2 = "Silent"
print(is_anagram_pythonic(str1, str2))  # Output: True