# Python basics 03 : class 2/03

Working with packages, eg Numpy https://numpy.org/doc/stable/user/absolute_beginners.html
and Pythonic code.

Ik you have problems installing packages (if pip is not recognized) see this https://www.dataquest.io/blog/install-pip-windows/  [see the get-pip.py-file](/01%20Python%20basics/get-pip.py)

In [ ]:
! pip install numpy

## Import Numpy

In [ ]:
import numpy
import numpy as np

from numpy import arange

## Creating arrays

Array elements must have the same type

In [ ]:
import numpy as np

list = [1, 5, 8, 10, 3]
print(list)
array = np.array(list)
print(array)

print(list*2)
print(array*2)

list.append(2)
# array.append(2) --> not possible! It's fixed size!

# 1D arrays
print(np.arange(10)) # exluded upperbound
print(np.zeros(10))
print(np.ones(10))
print(np.full(10,5))
print(np.random.randint(-5,6, 10))
print(np.random.random(10))

# 2D arrays
print(np.zeros((4,3))) # adding a tuple witj dimensions for more dimensional arrays
print(np.full((2,10),7))
print(np.random.randint(-10,10,(2,4,3)))

## Reshaping & converting an array


In [ ]:
import numpy as np

array = np.random.randint(-5,6,10)
print(array)

print("array is of type:",array.dtype)

array_float = array.astype('f')
print(array_float)

array_string = array.astype(str)
print(array_string)

array_2D = np.reshape(array, (2,5))
print(array_2D)

array_2D = np.reshape(array, (5,2))
print(array_2D)

# needs to be perfect fit!
# array_2D = np.reshape(array, (3,3)) --> ValueError: cannot reshape array of size 10 into shape (3,3)
# array_2D = np.reshape(array, (2,6)) --> cannot reshape array of size 10 into shape (2,6)

## Slicing arrays

[start:end:step]

- start: starting value
- end: ending value
- step: stepsize

In [ ]:
import numpy as np

array = np.array([6, 8, 6, 7, 6, 1, 8, 2, 0, 5])
print(array)

print(array[1:5:1])     # [8 6 7 6]
print(array[1:5:])      # [8 6 7 6]
print(array[1:5:2])     # [8 7]

print(array[0:5:1])     # [6 8 6 7 6]
print(array[:5:1])      # [6 8 6 7 6]

print(array[0::1])      # [6 8 6 7 6 1 8 2 0 5]
print(array[0:10:1])    # [6 8 6 7 6 1 8 2 0 5]

print(array[::-1])      # [5 0 2 8 1 6 7 6 8 6] --> reverse array
print(array[0:10:-1])   # []
print(array[10::-1])    # [5 0 2 8 1 6 7 6 8 6]

print(array[::2])       # [6 6 6 8 0]
print(array[::-2])      # [5 2 1 7 8]

## Working with arrays

In [ ]:
import numpy as np

a = np.arange(0,10)
b = np.arange(9,-1,-1)
print(a,b)  # [0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]

print(a+b)
print(a-b)
print(a*b)

print(np.where(a%2 ==0, a+1, a)) # creating an array with only odd numbers --> [1 1 3 3 5 5 7 7 9 9]

print(np.where(b > 5)) # you get the indexes back [0, 1, 2, 3]
print(np.where(b > 5,b,0))

print(a.sum())
print(a.min())
print(a.max())

print(np.sqrt(a))

### Exercise: It's magic time!

Read a 1D array and a number of rows! Convert this 1D array to a 2D array! Calculate the sum of each column and if all sums are equal... you are dealing with a magic table!

<b>input</b><br>
2 7 0 8 4 1 1 0 10<br>
3<br>
<b>output</b><br>
True

<pre>
2   7   0
8   4   1
1   0   10
<i>11  11  11</i> --> MAGIC TABLE
</pre>

In [94]:
import numpy as np

input_array = input("Input array").split()  # 2 7 0 8 4 1 1 0 10, first split the string into a list
array = np.array(input_array).astype(int)   # convert list to array and convert every element to integer!

rows = int(input("Number of rows"))
cols = len(array)//rows

matrix = np.reshape(array, (rows, cols))
print(matrix)

sums = np.sum(matrix, axis=0) 
print(sums)

sum = np.sum(sums)
if sum//cols == sums[0]:
    print("magic table")
else:
    print("no magic here!")

# other approach for checking if the table is magic
check = True
for value in sums:
    if value != sums[0]:
        check = False
        break

if check is True:
    print("magic table")
else:
    print("no magic here!")

[[ 2  7  0]
 [ 8  4  1]
 [ 1  0 10]]
[11 11 11]
magic table
magic table


## Pythonic code

In [95]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


### Exercise: Jokes

https://pypi.org/project/pyjokes/

Your task is to create a Python program that uses the pyjokes package to generate random jokes. The program should prompt the user to select a category of jokes and then display a random joke from that category.

- Install the pyjokes package using pip.
- Create a new Python script named joke_generator.py.
- Import the pyjokes package.
- Display a menu of joke categories to the user. The menu should include at least three categories, such as "programming", "general", and "knock-knock".
- Prompt the user to select a category by entering the corresponding number.
- Use the pyjokes package to generate a random joke from the selected category.
- Display the joke to the user.
- Ask the user if they want to hear another joke from the same category. If they say yes, generate and display another joke from the same category. If they say no, return to the main menu.

In [97]:
! pip install pyjokes

In [102]:
import pyjokes

def PrintJoke(category):
    joke = ""
    if category == "1":
        joke = pyjokes.get_joke(language="en", category= "neutral")
    elif category == "2":
        joke = pyjokes.get_joke(language="en", category= "chuck")
    elif category == "3":
        joke = pyjokes.get_joke(language="en", category= "all")
    print(joke)

category = input("Choos the category (1) neutral (2) chuck norris (3) all")

while category in "123":
    PrintJoke(category)
    while input("another one? ").lower() == "yes":
        PrintJoke(category)
    category = input("Choos the category (1) neutral (2) chuck norris (3) all, something else to stop")


3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn't find a table.
Chuck Norris can dereference NULL.
Chuck Norris finished World of Warcraft.
With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions.
Chuck Norris's unit tests don't run. They die.

