# Les 3 - Python basics - 27/02

- Numpy: arrays
- Pythonic

Hoe installeer je nieuwe packages: pip install package_naam in terminal

In de notebooks zet je gewoon een ! voor de pip install package_naam

Een een package erin zit, gebruik je hem door import package_naam bovenaan je script te zetten!

Let erop dat als je verschillende versies van Python naast mekaar hebt staan, dat er soms onduidelijkheden zijn in welke versie packages geinstalleerd werden! Typische Python-fout waar je lang kan achter zoeken. Oplossingen:
- oude versies verwijderen en pacakges opnieuw installeren
- of packages handmatig kopieren van de ene naar de andere versie (C:\Users\<>\AppData\Local\Programs\Python)

In [1]:
# zet installaties altijd in apart codeblokje
! pip install numpy

In [2]:
# verschillende import mogelijkheden
import numpy
import numpy as np
from numpy import arange

## Aanmaken arrays

In [39]:
import numpy as np

list = [1,2,3,4,5]
print(list)

array = np.array(list) # fixed size op het moment dat ze werden aangemaakt!
print(array)

list += [1,2,3]
print(list)

# array += [1,2,3] KAN NIET!!

print(list*2)   # list * 2 van grootte
print(array*2)  # array elementen * 2

print(np.arange(10))
print(np.arange(0,10,2))

print(np.zeros(5))
print(np.ones((5,3)))   # als je 2D array maakt op plek van size moet nu (rij,kolom)

print(np.full((5,3,2),4))
print(np.full(5,4))

print(np.eye(4))    # is altijd vierkante matrix (eenheidsmatrix) dus vandaar slechts 1 waarde meegeven als grootte

print(np.random.random((4,2)))
print(np.random.random(5))

print(np.random.random_integers(-10,10, 8)) # niet meer gebruiken, function is deprecated, call randint(-10, 10 + 1) instead
print(np.random.randint(-10,10, 8))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3]
[1, 2, 3, 4, 5, 1, 2, 3, 1, 2, 3, 4, 5, 1, 2, 3]
[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]
[4 4 4 4 4]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.56047513 0.63342869]
 [0.43589327 0.01756086]
 [0.16428643 0.28070296]
 [0.37451513 0.11922132]]
[0.42278445 0.78984789 0.49182709 0.93072688 0.19928837]
[ 9 10 -7 -6  4 -3  2 -8]
[ 5 -9 -8 -1  9 -3  6 -4]


C:\Users\elkeb\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:31: DeprecationWarning: This function is deprecated. Please call randint(-10, 10 + 1) instead


### Pythonic vs. Algoritmische manier van lijsten/arrays aanmaken

In [19]:
array = np.arange(-9,10,3)  # Pythonic
print(array)

list = [x for x in range(-9,10,3)] # Pythonic
print(list)

list = []
for x in range(-9,10,3):
    list.append(x)
print(list)

[-9 -6 -3  0  3  6  9]
[-9, -6, -3, 0, 3, 6, 9]
[-9, -6, -3, 0, 3, 6, 9]


## Arrays omvormen naar ander type

In [49]:
array = np.random.randint(-10,10, 8)
print(array, "array is van type =",type(array)) # procedurele functie
print(array, "array is van type =",array.dtype) # OO-property

array = array.astype('f') # omvormen van type, naar een float
# array = array.astype(float) --> zelfde maar op andere manier
print(array)
print(array, "array is van type =",array.dtype) # OO-property

[-2  1  8  6  4 -9  1  5] array is van type = <class 'numpy.ndarray'>
[-2  1  8  6  4 -9  1  5] array is van type = int32
[-2.  1.  8.  6.  4. -9.  1.  5.]
[-2.  1.  8.  6.  4. -9.  1.  5.] array is van type = float32
[-2.  1.  8.  6.  4. -9.  1.  5.]


## Arrays omvormen naar andere dimensies

Als ja van 1D naar 2D gaat moeten dimensies kloppen
- 1D 8 --> 2D 2 x 4
- 1D 9 --> 2D 3 x 3

In [55]:
import random

array = np.random.randint(-10,10, 8) 

matrix = np.reshape(array, (2,4))
print(matrix)


[[ 8  8 -2 -3]
 [ 1 -8  5 -6]]
[ -2   2  -6   8   9   3   9   0   3  -5   6   6  -2   1 -10  -5   5  -8
   3   0   0  -8  -8   4   3   9  -5   9   4   6   5  -8  -4   1  -3  -7
   8   1   7  -8   5   7   0]


In [76]:
# maak een matrix van een array van een random aantal elementen 
# met grootste deler moet aantal rijen zijn
# voorbeeld: 100 elementen, grootste deler is 50, dus 50 rijen en 2 kolommen
# voorbeeld: 27 elementen, grootste deler is 9, dus 9 rijen en 3 kolommen
# voorbeeld: speciaal geval met priemgetal bv, 13 elementen, grootste deler is 13, dus 13 rijen en 1 kolom

array = np.random.randint(-10,10, random.randint(10,50)) 
print(array)

delers = []
for x in range(2,array.shape[0]):
    if array.shape[0] % x == 0:
        delers.append(x)

if delers == []:
    print(np.reshape(array, (array.shape[0],1)))
else:
    print(np.reshape(array, (max(delers), array.shape[0]//max(delers))))


[ 9  8  4  7  7  0 -1 -3 -2  2  5  5 -8 -3]
[[ 9  8]
 [ 4  7]
 [ 7  0]
 [-1 -3]
 [-2  2]
 [ 5  5]
 [-8 -3]]
