# Les 26/02

Basis Python (les 1 --> 3)

zie markdown --> https://www.markdownguide.org/cheat-sheet/ 

## Herhalingsoefening

- Filter Even Getallen: geef een bovengrens in én toon alleen alle even getallen van 0 tot en met de bovengrens.
- Som van Cijfers in een String: geef een string in, zoek alle cijfers en tel ze op!
- Vind het Langste Woord: geef een zin in én zoek het langste woord!

In [ ]:
upper = int(input("Geef een bovengrens"))

for i in range(0,upper+1):
    if i % 2 == 0:
        print(i, end=" ")

0 2 4 6 8 10 12 14 16 18 20 

In [ ]:
text = input("Geef tekst in") # AZERTY12AZE7AZGH0 --> som = 1 + 2 + 7 = 10

sum = 0
for c in text:
    if c in "123456789":
        sum += int(c)
    # if c.isdigit():
    #    sum += int(c)
print(sum)

20


In [10]:
text = input("Geef tekst in")
words = text.split(" ")

longest = ""
for word in words:
    if len(word) > len(longest):
        longest = word

print(longest)

langste


## Functies

Schrijf een functie die controleert of een getal een priemgetal is.
Gebruik daarna deze funcie in je zoektocht naar het volgende priemgetal na een ingegeven getal!

In [16]:
def prime(x):
    check = True
    for i in range(2,x//2): # je moet maar tot de helft gaan
        if x % i == 0:
            check = False
    return check

number = int(input("Geef een getal"))

print(number,"is priemgetal = ", prime(number))

number+=1
while not prime(number):
    number+=1

print(number, "is het volgende priemgetal")

898 is priemgetal =  False
907 is het volgende priemgetal


## Collections

4 soorten collecties:
- lijsten: geordend & aanpasbaar []
- tuples: geordend & niet aanpasbaar ()
- sets: ongeordend & aanpasbaar, maar geen duplicaten {}
- dictionaries: geordend & aanpasbaar, maar geen duplicaten { key:value }

arrays --> numpy

### List []

In [80]:
everything = ["text", 1, 2, True, False, "a", 8.8] # NOOIT DOEN!!!
print(everything)

fruit = ["apple","kiwi","banana","lemon","strawberry"]
fruit.append("pineapple")
print(fruit)
fruit += ["orange", "mango"]
print(fruit)
fruit.append("apple")
print(fruit)

fruit.remove("lemon")
print(fruit)
fruit.remove("apple")
print(fruit) # eerste voorkomen van apple wordt verwijderd

print(len(fruit))

print(fruit[0])  # eerste
print(fruit[len(fruit)-1])  # laatste
print(fruit[6])  # laatste
print(fruit[-1]) # laatste
print(fruit[-2]) # voorlaatste
print(fruit[-7]) # eerste
# print(fruit[-8]) --> bestaat niet!

print("lemon" in fruit)
print("apple" in fruit)

for f in fruit:
    print(f, end=" ")

print()
fruit.sort()
print(fruit)
fruit.reverse()
print(fruit)


['text', 1, 2, True, False, 'a', 8.8]
['apple', 'kiwi', 'banana', 'lemon', 'strawberry', 'pineapple']
['apple', 'kiwi', 'banana', 'lemon', 'strawberry', 'pineapple', 'orange', 'mango']
['apple', 'kiwi', 'banana', 'lemon', 'strawberry', 'pineapple', 'orange', 'mango', 'apple']
['apple', 'kiwi', 'banana', 'strawberry', 'pineapple', 'orange', 'mango', 'apple']
['kiwi', 'banana', 'strawberry', 'pineapple', 'orange', 'mango', 'apple']
7
kiwi
apple
apple
apple
mango
kiwi
False
True
kiwi banana strawberry pineapple orange mango apple 
['apple', 'banana', 'kiwi', 'mango', 'orange', 'pineapple', 'strawberry']
['strawberry', 'pineapple', 'orange', 'mango', 'kiwi', 'banana', 'apple']


In [42]:
numbers = range(0,10)

squares = [x**2 for x in numbers]
print(squares)

even = range(0,20,2)
for x in even:
    print(x)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0
2
4
6
8
10
12
14
16
18


In [45]:
matrix = [ [1,2,3],[4,5,6]]

print(matrix)
for row in matrix:
    for element in row:
        print(element, end=" ")
    print(end="\n")

[[1, 2, 3], [4, 5, 6]]
1 2 3 
4 5 6 


### tuple ()

gebruiken vaststaande collecties --> weekdagen, maanden, seizoenen

In [49]:
kinderen = ("tuur","jan","mies","bob")

# kinderen.append("bla")

print(len(kinderen))
print(kinderen[0])
print(kinderen[-1])

4
tuur
bob


### set {}

GEEN DUPLICATEN & ONGEORDEND

In [ ]:
fruit = {"apple","kiwi","banana","lemon","strawberry"}
print(fruit)
fruit.add("pineapple")
print(fruit)
fruit.add("apple")
fruit.add("apple")
fruit.add("apple")
print(fruit)

{'banana', 'kiwi', 'apple', 'strawberry', 'lemon'}
{'banana', 'kiwi', 'apple', 'pineapple', 'strawberry', 'lemon'}
{'banana', 'kiwi', 'apple', 'pineapple', 'strawberry', 'lemon'}


### dictionary { key:value }

GEEN DUPLICATEN in KEYS!!! (wel in values!)

In [56]:
students = {"r1234":"Jan", 
            "r789":"Korneel"}
print(students)
students["r5677"] = "Piet"
print(students)
students["r5677"] = "Joris" # Piet wordt overschreven want geen duplicatien!
print(students)
students["r5678"] = "Joris" # Joris wordt wel toegevoegd met ander studentennummer
print(students)

{'r1234': 'Jan', 'r789': 'Korneel'}
{'r1234': 'Jan', 'r789': 'Korneel', 'r5677': 'Piet'}
{'r1234': 'Jan', 'r789': 'Korneel', 'r5677': 'Joris'}
{'r1234': 'Jan', 'r789': 'Korneel', 'r5677': 'Joris', 'r5678': 'Joris'}


### Oefeningen
- Reken het gemiddelde uit per student. Kan je dit ook per toets doen? Voorbeeld: [[8, 7, 6, 9], [9, 9, 8, 8], [6, 7, 8, 7]]
- Bereken de volgende zaken: alle getallen samen (unie), getallen die in allebei zitten (overeenkomst) en getallen die alleen in de eerste set zitten (verschil) Voorbeeld: {1, 2, 3, 4} en {3, 4, 5, 6}
- Zet woorden in een woordenboek, waarbij de eerste letter de sleutel is en de woorden die met die letter beginnen eronder staan. Voorbeeld: ["appel", "boom", "aap", "banaan", "citroen", "aardbei"] → {'a': [...], 'b': [...], 'c': [...]}

In [73]:
cijfers = [[8, 7, 6, 9], [9, 9, 8, 8], [6, 7, 8, 7]]

for student in cijfers:
    som = 0
    for toets in student:
        som += toets
    print("gemiddelde per student = ", som/len(student))

gemiddeldes = [0] * len(cijfers[0])
for i in range(0,len(cijfers)):
    for j in range(0, len(cijfers[i])):
        gemiddeldes[j] += cijfers[i][j]

print([x/len(cijfers) for x in gemiddeldes])



gemiddelde per student =  7.5
gemiddelde per student =  8.5
gemiddelde per student =  7.0
[7.666666666666667, 7.666666666666667, 7.333333333333333, 8.0]


## packages

https://pypi.org/

! pip install naam <br>
import naam

In [81]:
! pip install numpy


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [84]:
import numpy

lijst = [1,2,3,4,5]
array = numpy.array(lijst)

print(lijst)
print(array)

print(lijst*2)
print(array*2)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


### Slicen

[start:aantal:stap]

In [105]:
lijst = [x for x in range(0,20,2)] 
print(lijst)

array = numpy.arange(10)*2
print(array)

print(lijst[0])
print(array[0])

print(lijst[0:3])
print(array[0:3])

print(lijst[0:-1:2]) # van 0 tot einde met stap 2
print(array[0:-1:3])

print(lijst[-1:0])
print(lijst[::-1]) # REVERSE!!!

print(lijst[3])
print(lijst[3:])


print(array < 10)
print(numpy.where(array<10))

print(array % 3)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]
0
0
[0, 2, 4]
[0 2 4]
[0, 4, 8, 12, 16]
[ 0  6 12]
[]
[18, 16, 14, 12, 10, 8, 6, 4, 2, 0]
6
[6, 8, 10, 12, 14, 16, 18]
[ True  True  True  True  True False False False False False]
(array([0, 1, 2, 3, 4]),)
[0 2 1 0 2 1 0 2 1 0]


## Pythonic

In [106]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
