# Les 9: 30/04 - Images



In [1]:
! pip install Pillow


[notice] A new release of pip is available: 24.2 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Kleuren & RGB

https://htmlcolorcodes.com/color-names/

In [5]:
from PIL import ImageColor

print(ImageColor.getcolor("red","RGBA"))
print(ImageColor.getcolor("chocolate","RGBA"))
print(ImageColor.getcolor("IndianRed", "RGBA"))

(255, 0, 0, 255)
(210, 105, 30, 255)
(205, 92, 92, 255)


## Manipuleren van beelden

https://picsum.photos/
https://www.pexels.com/



In [10]:
from PIL import Image

img = Image.open("cat.jpg")
print(img)
img.show()

print(img.size)
w, h = img.size
print(w)
print(img.filename)


<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=640x427 at 0x1DE6C127DA0>
(640, 427)
640
C:\Users\elkeb\OneDrive - Thomas More\GitHub 24-25\Scripting-Students\07 Images\cat.jpg


In [24]:
cat = img.crop((230,80,360,200))
cat.save("cropped.jpg")
cat.show()

copy = img.copy()
copy.paste(cat, (0,0))
copy.paste(cat, (100,30))
copy.show()

half = img.resize((w//2, h//2))
half.save("half.jpg")

half.rotate(90).save("rotated90.jpg")


In [ ]:
hotpink = Image.new("RGBA",(100,100), "hotpink")
hotpink.save("hotpink.png") # png --> transparantie!!

In [ ]:
img = Image.open("cropped.jpg")

for x in range(0, img.width):
    for y in range(0, img.height):
        r,g,b = img.getpixel((x,y))
        print(img.getpixel((x,y)))
        img.putpixel((x,y),(0,g,b)) # haal rood uit image

img.show()

(249, 244, 240)
(250, 245, 241)
(250, 245, 241)
(250, 245, 241)
(249, 244, 240)
(247, 242, 238)
(246, 241, 237)
(245, 240, 236)
(241, 236, 232)
(238, 233, 229)
(234, 229, 225)
(231, 226, 222)
(230, 225, 221)
(230, 225, 221)
(232, 227, 223)
(235, 227, 224)
(231, 220, 216)
(232, 219, 213)
(231, 218, 212)
(233, 220, 214)
(236, 223, 217)
(239, 226, 220)
(240, 227, 221)
(240, 227, 221)
(242, 229, 223)
(241, 228, 222)
(240, 227, 221)
(239, 226, 220)
(238, 225, 219)
(237, 224, 218)
(236, 223, 217)
(236, 223, 217)
(239, 226, 218)
(239, 226, 218)
(240, 227, 219)
(241, 228, 220)
(243, 230, 222)
(245, 232, 224)
(247, 232, 225)
(248, 233, 226)
(249, 232, 225)
(250, 233, 226)
(251, 234, 227)
(252, 235, 228)
(253, 234, 228)
(251, 232, 226)
(249, 230, 224)
(247, 229, 225)
(243, 232, 228)
(240, 230, 228)
(237, 227, 225)
(234, 224, 222)
(233, 223, 221)
(234, 224, 222)
(236, 226, 224)
(238, 228, 226)
(236, 226, 224)
(233, 223, 221)
(228, 218, 216)
(224, 214, 212)
(223, 213, 211)
(225, 215, 213)
(229, 21

## Werken met opencv
https://opencv.org/

In [28]:
! pip install opencv-python


[notice] A new release of pip is available: 24.2 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import cv2

img = cv2.imread("cat.jpg")
print(img)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite("dog_gray.jpg", gray)

gray = Image.open("dog_gray.jpg")
gray.show()

[[[218 215 217]
  [217 214 216]
  [217 214 216]
  ...
  [ 39  29  12]
  [ 39  29  12]
  [ 39  29  12]]

 [[221 218 220]
  [220 217 219]
  [219 216 218]
  ...
  [ 38  28  11]
  [ 38  28  11]
  [ 39  29  12]]

 [[218 215 217]
  [217 214 216]
  [217 214 216]
  ...
  [ 37  27  10]
  [ 37  27  10]
  [ 38  28  11]]

 ...

 [[188 172 156]
  [189 173 157]
  [191 175 159]
  ...
  [228 226 226]
  [227 225 225]
  [227 225 225]]

 [[189 173 157]
  [190 174 158]
  [192 176 160]
  ...
  [228 226 226]
  [227 225 225]
  [227 225 225]]

 [[190 174 158]
  [191 175 159]
  [193 177 161]
  ...
  [228 226 226]
  [227 225 225]
  [227 225 225]]]


In [36]:
import cv2
import numpy as np

# Create a simple black image
img = np.zeros((300, 300, 3), dtype=np.uint8)

# Draw some basic shapes
cv2.rectangle(img, (50, 50), (250, 150), (255, 0, 0), 10)
cv2.circle(img, (150, 200), 50, (255, 0, 0), -1)
cv2.line(img, (0, 0), (300, 300), (255, 255, 255), 2)

# Add text
cv2.putText(img, "OpenCV", (75, 100), 
            cv2.FONT_HERSHEY_SIMPLEX, 1, 
            (255, 255, 255), 2)

# Save image
cv2.imwrite("opencv.jpg", img)

True

In [40]:
import cv2
import numpy as np

# Load image and convert to grayscale
img = cv2.imread('cat.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply threshold to get binary image
ret, thresh = cv2.threshold(gray, 127, 255, 0)

# Find contours
contours, hierarchy = cv2.findContours(thresh, 
                               cv2.RETR_TREE, 
                               cv2.CHAIN_APPROX_SIMPLE)

# Draw contours on original image
contour_img = img.copy()
cv2.drawContours(contour_img, contours, -1, (0, 255, 0), 2)

cv2.imwrite("cat_contours.jpg", contour_img)

True

In [43]:
import cv2

# Load image and convert to grayscale
img = cv2.imread('cat_silhouette.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Simple edge detection with Canny
edges = cv2.Canny(gray, 100, 200)

# Save result
cv2.imwrite('cat_silhouette_edges.png', edges)

True

We gaan onze afbeelding encoderen naar een file 

https://en.wikipedia.org/wiki/Run-length_encoding



In [52]:
img = Image.open("cat_silhouette.jpg")

print(img.size)

file = open("encoding.txt","w")

for y in range(0, img.height):
    count = 0
    prev = True
    for x in range(0, img.width):
        white = img.getpixel((x,y))[0] == 255
        if prev == white:
            count += 1
        else:
            file.write(str(count+1) + " ")
            count = 0
    file.write(str(count)+"\n")

file.close()

(1601, 1601)


In [58]:
hotpink = Image.new("RGBA",(1601,1601), "hotpink")

with open("encoding.txt","r") as file:
    count = 0
    black = False
    for line in file.readlines():
        pixels = line.split()
        x = 0
        for pixel in pixels:
            if black:
                for i in range(0,int(pixel)):
                    hotpink.putpixel((x,count),(255,255,255)) 
                    x += 1
            else:
                x += int(pixel)
            black = not black
        count += 1

hotpink.save("cat_hotpink_from_encoding.png") # png --> transparantie!!

## Object detectie

https://en.wikipedia.org/wiki/You_Only_Look_Once 

In [60]:
import cv2

# Load image and convert to grayscale
img = cv2.imread('street.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Load pre-trained Haar Cascade for face detection
face_cascade = cv2.CascadeClassifier(
  cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Detect faces
faces = face_cascade.detectMultiScale(gray, 
                                scaleFactor=1.1, minNeighbors=5)

# Draw rectangles around detected faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

cv2.imwrite("street_faces.jpg", img)

True

In [61]:
! pip install ultralytics


[notice] A new release of pip is available: 24.2 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [65]:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model("street.jpg", save=True)

results_video = model(source="video.mp4", save=True)


image 1/1 c:\Users\elkeb\OneDrive - Thomas More\GitHub 24-25\Scripting-Students\07 Images\street.jpg: 448x640 3 persons, 8 cars, 1 truck, 2 traffic lights, 3 dogs, 210.9ms
Speed: 7.0ms preprocess, 210.9ms inference, 10.7ms postprocess per image at shape (1, 3, 448, 640)
Results saved to runs\detect\predict3


WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/605) c:\Users\elkeb\OneDrive - Thomas More\GitHub 24-25\Scripting-Students\07 Images\video.mp4: 384x640 8 persons, 4 cars, 1 bus,

Tel het aantal mensen op de grote markt in brussel

https://www.meteoblue.com/nl/weer/webcams/brussel_belgi%C3%AB_2800866 
https://opendata.brussels.be/explore/dataset/webcams/information/



In [ ]:
import requests

response = requests.get("<image url>").content

ImageFile = open("brussel.jpg", "wb")
ImageFile.write(response)
ImageFile.close()

img = Image.open("brussel.jpg")
model = YOLO("yolov8n.pt")

CountThings = model("brussel.jpg", save=True)


image 1/1 c:\Users\elkeb\OneDrive - Thomas More\GitHub 24-25\Scripting-Students\07 Images\brussel.jpg: 384x640 9 persons, 420.0ms
Speed: 15.0ms preprocess, 420.0ms inference, 12.4ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs\detect\predict2
