# Recap 19 april

## Numpy

In [2]:
import numpy as np 

list = [1,2,3,4,5] 
print(list) 
array = np.array([1,2,3,4,5]) 
print(array)

print(list*2)
print(array*2)

print(np.arange(10)) 
print(np.zeros((10,)))              
print(np.ones((2,3)))             
print(np.full((5,), 7))
print(np.eye(4))               
print(np.random.random((1,4)))  
print(np.random.random_integers(-10, 10, (4,4)))

a = np.arange(8)**3    # exponent 3 --> 0^3 1^3 2^3 3^3 ...
print(a)
print(a[2:5])
print(a[:4])           
print(a[4:])
a[::3] = -1         
print(a)   
print(a[::-1])  #reverse          
print(a[1::2])  # odd indexes           

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[7 7 7 7 7]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.97276576 0.60103848 0.10474341 0.85231951]]
[[  1   3   3  -8]
 [  2   8 -10   5]
 [  1  -2  -9  -8]
 [  2   5  -4  10]]
[  0   1   8  27  64 125 216 343]
[ 8 27 64]
[ 0  1  8 27]
[ 64 125 216 343]
[ -1   1   8  -1  64 125  -1 343]
[343  -1 125  64  -1   8   1  -1]
[  1  -1 125 343]


C:\Users\elkeb\AppData\Local\Temp\ipykernel_7296\3012640359.py:17: DeprecationWarning: This function is deprecated. Please call randint(-10, 10 + 1) instead
  print(np.random.random_integers(-10, 10, (4,4)))


## Pythonic code om lijst te maken

In [3]:
lijst = []
for x in range(0,5):
    lijst.append(x**2)
print(lijst)
 
squares = [x ** 2 for x in range(0,5)]
print (squares)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]


## Libraries & packages

! pip install <library>

Werken met regexen

In [14]:
string = 'Hi\nHe\tllo\n'
print(string)
 
raw_string = r'Hi\nHello\nblabla'
print(raw_string)
print(raw_string.split(r'\n'))

# regex om mee te werken en hetzelfde te doen [^(\\n)]
# deze regex geeft alle leters, dus alles dat niet gelijk is aan \n

import re
result = re.findall(r"[^(\\n)]", raw_string) 
print(result)

# [^(\\n)]+ deze regex geeft 1 of meer voorkomen

result = re.findall(r"[^(\\n)]+", raw_string) 
print(result)

result = re.findall(r"[^(\\n)]\w+", raw_string) 
print(result)


Hi
He	llo

Hi\nHello\nblabla
['Hi', 'Hello', 'blabla']
['H', 'i', 'H', 'e', 'l', 'l', 'o', 'b', 'l', 'a', 'b', 'l', 'a']
['Hi', 'Hello', 'blabla']
['Hi', 'Hello', 'blabla']


## Oefening

- Request a person from the RandomUser API at https://randomuser.me/api/ and print his/her full name
- Scrape all country information of his/her country from https://www.scrapethissite.com/pages/simple/
- Request the exact location from the same person and plot this data on a map (up to city level)

### Deel 1 = random user

In [45]:
import requests, json
response = requests.get('https://randomuser.me/api/')

if (response.status_code==200):
    random_person = json.loads(response.text)
    # print(random_person)
    first = random_person['results'][0]['name']['first']
    last = random_person['results'][0]['name']['last']
    streetname = random_person['results'][0]['location']['street']['name']
    streetnr = random_person['results'][0]['location']['street']['number']
    city = random_person['results'][0]['location']['city']
    postcode = random_person['results'][0]['location']['postcode']
    country = random_person['results'][0]['location']['country']

    print(first, last)

Alex Ross


### Deel 2 = land informatie

Belangrijk dat je weet hoe landeninfo eruit ziet:

<div class="col-md-4 country">
<h3 class="country-name">
    <i class="flag-icon flag-icon-au"></i>
    Australia
</h3>
<div class="country-info">
    <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
    <strong>Population:</strong> <span class="country-population">21515754</span><br>
    <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
</div>
</div>

In [67]:
from bs4 import BeautifulSoup

print(country)

response = requests.get('https://www.scrapethissite.com/pages/simple/')
soup = BeautifulSoup(response.text)
divs = soup.find_all('div', {"class":"col-md-4 country"})
for item in divs:
    countryname = item.find_all('h3', {'class':"country-name"})
    if countryname[0].get_text().strip() == country:
        print("Capital:", item.find('span', {'class':"country-capital"}).get_text().strip())
        print("Population:", item.find('span', {'class':"country-population"}).get_text().strip())
        print("Area:", item.find('span', {'class':"country-area"}).get_text().strip())


Australia
Capital: Canberra
Population: 21515754
Area: 7686850.0


### Deel 3 = plotten

Plotten met folium

In [80]:
# ! pip install folium
# ! pip install geopy


import folium
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="test")
loc = geolocator.geocode(city+','+ country)
print(city, (loc.latitude, loc.longitude))

m = folium.Map(location=[loc.latitude, loc.longitude])
m

(-30.7464139, 121.473223)
